[package]
name = "rocket"
version = "0.1.0"
authors = ["Florent Peterschmitt <florent@peterschmitt.fr>"]

[dependencies]
clap = "2"
reqwest = "0.9.5"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
