/* INTERRUPTIONS */

//INTERRUPT ENABLE
#define INT0_IE INTCONbits.INT0IE
#define INT1_IE INTCON3bits.INT1IE
#define INT2_IE INTCON3bits.INT2IE
#define INT3_IE INTCON3bits.INT3IE

//GENERAL INTERRUPT ENABLE
#define INT_GIE INTCONbits.GIE

//INTERRUPT FLAGS
#define INT0_FLAG INTCONbits.INT0IF
#define INT1_FLAG INTCON3bits.INT1IF
#define INT2_FLAG INTCON3bits.INT2IF
#define INT3_FLAG INTCON3bits.INT3IF

//INTERRUPT EDGES
#define INT0_EDG INTCON2bits.INTEDG0
#define INT1_EDG INTCON2bits.INTEDG1
#define INT2_EDG INTCON2bits.INTEDG2
#define INT3_EDG INTCON2bits.INTEDG3
/******************/
